export const MIN_IDENTIFIER_LEN = 2
export const MAX_IDENTIFIER_LEN = 100
export const MIN_PASSWORD_LEN = 3
export const MAX_PASSWORD_LEN = 128
export const USERNAME_REGEX = /^[\w.@+-]+$/
export const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
export const RECIPE_COMMON_FORBIDDEN_CHARS = /[<>]/

export const RECIPE = {
  TITLE: { MIN: 3, MAX: 50, FORBIDDEN_CHARS: RECIPE_COMMON_FORBIDDEN_CHARS },
  DESCRIPTION: { MIN: 3, MAX: 500, FORBIDDEN_CHARS: RECIPE_COMMON_FORBIDDEN_CHARS },
  SERVINGS: { MIN: 1, MAX: 10000 },
  INGREDIENTS: {
    CATEGORY: {
      MIN: 1,
      MAX: 5,
      TITLE: { MIN: 1, MAX: 50, FORBIDDEN_CHARS: RECIPE_COMMON_FORBIDDEN_CHARS },
    },
    ITEM: {
      MIN: 1,
      MAX: 10,
      AMOUNT: { MIN: 0.01, MAX: 10000 },
      UNIT: { MIN: 1, MAX: 10, FORBIDDEN_CHARS: RECIPE_COMMON_FORBIDDEN_CHARS },
      NAME: { MIN: 2, MAX: 30, FORBIDDEN_CHARS: RECIPE_COMMON_FORBIDDEN_CHARS },
      NOTES: { MIN: 2, MAX: 50, FORBIDDEN_CHARS: RECIPE_COMMON_FORBIDDEN_CHARS },
    },
  },
  PREPARATION_STEPS: {
    MIN: 1,
    MAX: 5,
    TITLE: { MIN: 3, MAX: 70, FORBIDDEN_CHARS: RECIPE_COMMON_FORBIDDEN_CHARS },
    DESCRIPTION: { MIN: 5, MAX: 3000, FORBIDDEN_CHARS: RECIPE_COMMON_FORBIDDEN_CHARS },
  },
}
